apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop-deployment
  namespace: online-shop
  labels:
    app: online-shop
spec:
  replicas: 0  
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
        - name: online-shop-container
          image: johncorner158/online_shop_app:latest
          ports:
            - containerPort: 80
